version: '3'
services:
  backend:
    build: './server'
    ports:
      - "4001:4001"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_DATABASE: siiliwalldev
      NODE_ENV: production
  db:
    build: "./mysql"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITARY: 1
    restart:
      always
    ports:
      - "8081:80"
